<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2015 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="#all">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" use-character-maps="spaces" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:character-map name="spaces">
		<xsl:output-character character="&#160;" string="&amp;nbsp;"/>
	</xsl:character-map>
	<xsl:param name="altova:bGeneratingFromPxf" select="false()"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:param name="SV_BaseOutputFileName" as="xs:string?">
		<xsl:sequence select="for $i in altovaext:get-base-output-uri(), $j in tokenize( $i, &apos;[/\\]&apos; )[last()] return replace( $j, &apos;\.[^\.\s#%;]*$&apos;, &apos;&apos; )" use-when="function-available(&apos;altovaext:get-base-output-uri&apos;)"/>
	</xsl:param>
	<xsl:param name="SV_GeneratedFileNamePrefix" select="if ( $SV_BaseOutputFileName ) then $SV_BaseOutputFileName else &apos;10169&apos;" as="xs:string?"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:import-schema schema-location="10169_rpt.xsd" use-when="system-property('xsl:is-schema-aware')='yes'"/>
	<xsl:variable name="altova:CssImages" select="()"/>
	<xsl:template match="/">
		<xsl:call-template name="altova:Root"/>
	</xsl:template>
	<xsl:template name="altova:Root">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2015 sp2 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=9"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">
					<xsl:value-of select="document('style.css')" disable-output-escaping="yes" />
				</style>
				<style type="text/css">@page { margin-left:0.60in; margin-right:0.60in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<span style="font-size:16pt; ">
					<xsl:text>Сведения о подразделениях пожарной охраны на объектах электроэнергетики </xsl:text>
				</span>
				<br/>
				<span style="font-size:16pt; ">
					<xsl:text>за ____________ _________года</xsl:text>
				</span>
				<br/>
				<hr/>
				<span>
					<xsl:text>Наименование отчитывающейся организации:</xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>ОГРН/ИНН/ОКПО:</xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>Почтовый адрес:</xsl:text>
				</span>
				<br/>
				<br/>
				<span>
					<xsl:text>Раздел 1. Сведения о подразделениях пожарной охраны на объектах электроэнергетики</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_0" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Код</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>строки</xsl:text>
									</span>
									<br/>
								</th>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Наименование объекта, охраняемого подразделением пожарной охраны по</xsl:text>
											</span>
											<br/>
											<span>
												<xsl:text>договору</xsl:text>
											</span>
											<br/>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Местонахождение охраняемого объекта</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Наименование подразделения пожарной охраны, обеспечивающего охрану объекта от пожара</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Номер договора о тушении пожаров и срок договора</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Количество личного состава пожарной охраны, чел.</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Количество пожарных автоцистерн, ед.</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Количество пожарных автонасосов, ед.</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Другая пожарная техника (перечислить)</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Количество работников, входящих в добровольные пожарные формирования,</xsl:text>
											</span>
											<br/>
											<span>
												<xsl:text>чел.</xsl:text>
											</span>
											<br/>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Наличие у пожарного подразделения функций по проведению аварийно-спасательных работ</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>ФИО лица, отвечающего за вопросы пожарной безопасности</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Рабочий телефон лица, отвечающего за вопросы пожарной безопасности</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Мобильный телефон лица, отвечающего за вопросы пожарной безопасности</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Электронная почта лица, отвечающего за вопросы пожарной безопасности</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:variable name="altova:sComment">
									<xsl:text>[if IE]&gt;&lt;th style=&quot;vertical-align:bottom; &quot;&gt;&lt;table align=&quot;center&quot; style=&quot;margin-left: auto; margin-right: auto&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;text-align: left; writing-mode: tb-rl; filter: fliph flipv&quot;&gt;&lt;div&gt;&lt;![endif]</xsl:text>
								</xsl:variable>
								<xsl:comment>
									<xsl:value-of select="$altova:sComment"/>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if !IE]&gt;</xsl:text>
								</xsl:comment>
								<xsl:element name="th">
									<xsl:attribute name="style">
										<xsl:variable name="altova:sComment2">
											<xsl:text>text-align:left; vertical-align:bottom; </xsl:text>
										</xsl:variable>
										<xsl:value-of select="$altova:sComment2"/>
									</xsl:attribute>
									<xsl:element name="div">
										<xsl:attribute name="style">-moz-transform: translate(50%, 50%) rotate(-90deg); -moz-transform-origin: 0% 50%;-webkit-transform: translate(50%, 50%) rotate(-90deg); -webkit-transform-origin: 0% 50%</xsl:attribute>
										<xsl:comment>
											<xsl:text>&lt;![endif]</xsl:text>
										</xsl:comment>
										<div>
											<span>
												<xsl:text>Примечание</xsl:text>
											</span>
										</div>
										<xsl:comment>
											<xsl:text>[if !IE]&gt;</xsl:text>
										</xsl:comment>
									</xsl:element>
								</xsl:element>
								<xsl:comment>
									<xsl:text>&lt;![endif]</xsl:text>
								</xsl:comment>
								<xsl:comment>
									<xsl:text>[if IE]&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;![endif]</xsl:text>
								</xsl:comment>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>4</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>5</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>6</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>7</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>8</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>9</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>10</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>11</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>12</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>13</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>14</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>15</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>16</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strfree">
											<tr>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column4">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column5">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column6">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column7">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column8">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column9">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column10">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column11">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column12">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column13">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column14">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column15">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<br/>
				<br/>
			</body>
		</html>
	</xsl:template>
	<xsl:function name="altova:is-cell-empty" as="xs:boolean">
		<xsl:param name="altova:cell" as="element()"/>
		<xsl:sequence select="altova:is-node-empty( $altova:cell )"/>
	</xsl:function>
	<xsl:function name="altova:is-node-empty" as="xs:boolean">
		<xsl:param name="altova:node" as="element()"/>
		<xsl:sequence select="every $altova:child in $altova:node/child::node() satisfies ( ( boolean( $altova:child/self::text() ) and string-length( $altova:child ) = 0 ) or ( ( boolean( $altova:child/self::div ) or boolean( $altova:child/self::span ) or boolean( $altova:child/self::a ) ) and altova:is-node-empty( $altova:child ) ) )"/>
	</xsl:function>
	<xsl:function name="altova:col-span" as="xs:integer">
		<xsl:param name="altova:cell" as="element()"/>
		<xsl:sequence select="if ( exists( $altova:cell/@colspan ) ) then xs:integer( $altova:cell/@colspan ) else 1"/>
	</xsl:function>
	<xsl:template match="@* | node()" mode="altova:generate-table">
		<xsl:param name="altova:generate-cols"/>
		<xsl:copy>
			<xsl:apply-templates select="@* | node()" mode="#current">
				<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
			</xsl:apply-templates>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="tbody" mode="altova:generate-table">
		<xsl:param name="altova:generate-cols"/>
		<xsl:choose>
			<xsl:when test="empty(tr)">
				<xsl:copy>
					<tr>
						<td/>
					</tr>
				</xsl:copy>
			</xsl:when>
			<xsl:otherwise>
				<xsl:copy>
					<xsl:apply-templates select="@* | node()" mode="#current">
						<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
					</xsl:apply-templates>
				</xsl:copy>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template match="th | td" mode="altova:generate-table">
		<xsl:choose>
			<xsl:when test="altova:is-cell-empty( . )">
				<xsl:copy>
					<xsl:apply-templates select="@*" mode="#current"/>
					<xsl:text>&#160;</xsl:text>
				</xsl:copy>
			</xsl:when>
			<xsl:otherwise>
				<xsl:copy>
					<xsl:apply-templates select="@* | node()" mode="#current"/>
				</xsl:copy>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:function name="altova:GetChartYValuesForSingleSeries">
		<xsl:param name="seqCategoryLeafPos" as="node()*"/>
		<xsl:param name="nodeSeriesLeafPos" as="node()"/>
		<xsl:param name="bValuesInCategory" as="xs:boolean"/>
		<xsl:for-each select="$seqCategoryLeafPos">
			<xsl:element name="altova:Value">
				<xsl:value-of select="altova:GetChartYValueForSingleSeriesPos($nodeSeriesLeafPos, ., $bValuesInCategory)"/>
			</xsl:element>
		</xsl:for-each>
	</xsl:function>
	<xsl:function name="altova:GetChartYValueForSingleSeriesPos">
		<xsl:param name="nodeSeriesLeafPos" as="node()"/>
		<xsl:param name="nodeCategoryLeafPos" as="node()"/>
		<xsl:param name="bValuesInCategory" as="xs:boolean"/>
		<xsl:variable name="altova:seqCategoryContextIds" select="$nodeCategoryLeafPos/altova:Context/@altova:ContextId" as="xs:string*"/>
		<xsl:variable name="altova:seqSeriesContextIds" select="$nodeSeriesLeafPos/altova:Context/@altova:ContextId" as="xs:string*"/>
		<xsl:variable name="altova:sCommonContextId" select="for $i in $altova:seqCategoryContextIds return if (some $j in $altova:seqSeriesContextIds satisfies $i eq $j) then $i else ()" as="xs:string*"/>
		<xsl:choose>
			<xsl:when test="count($altova:sCommonContextId) gt 1">
				<xsl:message select="concat('Found several values instead of a single one (contexts: ', string-join($altova:sCommonContextId, ', '), ').')" terminate="yes"/>
			</xsl:when>
			<xsl:when test="count($altova:sCommonContextId) lt 1">
				<xsl:message select="concat('XBRL Chart: Info: No value found for position labeled &quot;', $nodeCategoryLeafPos/@altova:sLabel, '&quot;')" terminate="no"/>
				<xsl:sequence select="'altova:no-value'"/>
			</xsl:when>
			<xsl:when test="$bValuesInCategory">
				<xsl:sequence select="xs:string($nodeCategoryLeafPos/altova:Context[@altova:ContextId eq $altova:sCommonContextId]/@altova:Value)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:sequence select="xs:string($nodeSeriesLeafPos/altova:Context[@altova:ContextId eq $altova:sCommonContextId]/@altova:Value)"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>
	<xsl:function name="altova:GetChartLabelForPos" as="xs:string">
		<xsl:param name="nodeParam" as="node()"/>
		<xsl:value-of select="string-join($nodeParam/ancestor-or-self::altova:Pos/@altova:sLabel, ' ')"/>
	</xsl:function>
	<xsl:function name="altova:convert-length-to-pixel" as="xs:decimal">
		<xsl:param name="altova:length"/>
		<xsl:variable name="normLength" select="normalize-space($altova:length)"/>
		<xsl:choose>
			<xsl:when test="ends-with($normLength, 'px')">
				<xsl:value-of select="substring-before($normLength, 'px')"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'in')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'in')) * $altova:nPxPerIn"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'cm')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'cm')) * $altova:nPxPerIn div 2.54"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'mm')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'mm')) * $altova:nPxPerIn div 25.4"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pt')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pt')) * $altova:nPxPerIn div 72.0"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pc')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pc')) * $altova:nPxPerIn div 6.0"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$normLength"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>
	<xsl:function name="altova:convert-length-to-mm" as="xs:decimal">
		<xsl:param name="altova:length"/>
		<xsl:variable name="normLength" select="normalize-space($altova:length)"/>
		<xsl:choose>
			<xsl:when test="ends-with($normLength, 'px')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'px')) div $altova:nPxPerIn * 25.4"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'in')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'in')) * 25.4"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'cm')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'cm')) * 10"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'mm')">
				<xsl:value-of select="substring-before($normLength, 'mm') "/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pt')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pt')) * 25.4 div 72.0"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pc')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pc')) * 25.4 div 6.0"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="number($normLength) div $altova:nPxPerIn * 25.4"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>
</xsl:stylesheet>
