<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2015 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="#all">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" use-character-maps="spaces" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:character-map name="spaces">
		<xsl:output-character character="&#160;" string="&amp;nbsp;"/>
	</xsl:character-map>
	<xsl:param name="altova:bGeneratingFromPxf" select="false()"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:param name="SV_BaseOutputFileName" as="xs:string?">
		<xsl:sequence select="for $i in altovaext:get-base-output-uri(), $j in tokenize( $i, &apos;[/\\]&apos; )[last()] return replace( $j, &apos;\.[^\.\s#%;]*$&apos;, &apos;&apos; )" use-when="function-available(&apos;altovaext:get-base-output-uri&apos;)"/>
	</xsl:param>
	<xsl:param name="SV_GeneratedFileNamePrefix" select="if ( $SV_BaseOutputFileName ) then $SV_BaseOutputFileName else &apos;30035&apos;" as="xs:string?"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:import-schema schema-location="30035.xsd" use-when="system-property('xsl:is-schema-aware')='yes'"/>
	<xsl:variable name="altova:CssImages" select="()"/>
	<xsl:template match="/">
		<xsl:call-template name="altova:Root"/>
	</xsl:template>
	<xsl:template name="altova:Root">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2015 sp2 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=9"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.60in; margin-right:0.60in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<br/>
				<span>
					<xsl:text>Раздел I. Общие сведения</xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>Отчетный период: 20__ год.</xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>Количество разрезов, включенных в отчет: административных (структурных единиц)__________, технических единиц___________</xsl:text>
				</span>
				<br/>
				<br/>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_0" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<tbody style="caption-side:top; table-layout:fixed; vertical-align:top; ">
							<tr style="height:6.31in; table-layout:fixed; ">
								<td style="caption-side:top; text-align:left; width:10.99in; " width="1000">
									<span>
										<xsl:text>1.	Сведения о лицензиях на добычу угля :</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	номер и дата выдачи лицензии __________________________</xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=3]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<span>
										<xsl:text>срок действия лицензии с </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=5]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> по </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=6]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>2.	Производственная мощность на конец отчетного года&#160; </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=7]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; тыс.т</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	ввод мощности за отчетный период&#160;&#160;&#160; ________________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=8]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> тыс.т</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	выбытие мощностей за отчетный период_____________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=9]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>тыс.т</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	&#160;&#160;&#160;&#160;&#160;&#160; использование среднегодовой мощности __________&#160; </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=10]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> %</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>3.	Год сдачи в эксплуатацию / последней реконструкции ______ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=11]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>4.	Месторождение&#160; _____________________________________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=12]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>5.	Максимальная глубина разработки на конец&#160; года ______ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=15]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; м.</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>6.	Приток воды: нормальный&#160;&#160;&#160;&#160; ______&#160; </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=16]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> м3/ч</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	максимальный сезонный _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=17]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> м3/ч</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>7.	Число разрабатываемых пластов на конец года (в сводных отчетах по компании - не заполнять)&#160;&#160; _______ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=18]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>8.	Их суммарная мощность геологическая/рабочая _______ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=19]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; / </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=20]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>м</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>9.	Угол падения разрабатываемых пластов:</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	&#160;&#160;&#160;&#160;&#160;&#160; от&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=21]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> о</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	&#160;&#160;&#160;&#160;&#160;&#160; до _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=22]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> о </xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>10.	Средний объемный вес угля __________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=23]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> т/м3	</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>11.	Мощность покрывающих (вмещающих) пород на конец года _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=24]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; м</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>12.	Средний объемный вес вскрышных пород _______ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_010[@code=25]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> т/м3</xsl:text>
									</span>
									<br/>
									<br/>
								</td>
								<td style="caption-side:top; width:inherit; " width="1000">
									<span>
										<xsl:text>13.	Балансовые запасы угля (кат. А+В+С1) </xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	на конец отчетного года </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_011[@code=26]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; тыс.т</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>в том числе по маркам:&#160; </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_011[@code!=26]">
													<xsl:for-each select="concat( &quot;        &quot; ,  @name ,  &quot; _____  &quot;, @column1 )">
														<p>
															<xsl:choose>
																<xsl:when test=". instance of element() or . instance of document-node()">
																	<xsl:apply-templates/>
																</xsl:when>
																<xsl:otherwise>
																	<xsl:value-of select="."/>
																</xsl:otherwise>
															</xsl:choose>
														</p>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>14	Промышленные запасы угля на конец</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	отчетного года&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _______________________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_012[@code=27]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> тыс.т</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>в том числе по маркам:&#160;&#160; </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_012[@code!=27]">
													<xsl:for-each select="concat( &quot;        &quot; ,  @name ,  &quot; _____  &quot;, @column1 )">
														<p>
															<xsl:choose>
																<xsl:when test=". instance of element() or . instance of document-node()">
																	<xsl:apply-templates/>
																</xsl:when>
																<xsl:otherwise>
																	<xsl:value-of select="."/>
																</xsl:otherwise>
															</xsl:choose>
														</p>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>в том числе подготовленные&#160;&#160; __________________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=28]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> тыс.т</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>&#160;&#160;&#160;&#160; из них готовые к выемке&#160;&#160;&#160; __________________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=29]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; тыс.т</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>15.	Эксплуатационные потери угля&#160; _________________ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=30]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> тыс.т</xsl:text>
									</span>
									<br/>
									<br/>
									<span>
										<xsl:text>16.	Количество уступов на конец отчетного года</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	угольных&#160;&#160;&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=31]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<span>
										<xsl:text>	породных&#160;&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=32]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span>
										<xsl:text>17.	Действующая длина уступов</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	угольных&#160;&#160;&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=33]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text>&#160; м</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	породных&#160;&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=34]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> м</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>18.	Среднедействующая высота уступов</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	угольных&#160;&#160;&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=35]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> м</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>	породных&#160;&#160; _____ </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_013[@code=36]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span>
										<xsl:text> м</xsl:text>
									</span>
									<br/>
									<br/>
								</td>
							</tr>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Раздел II. Добыча угля и вскрышные работы за отчетный год</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_1" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Наименование</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>№ строки</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Единица измерения</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Фактически</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Зольность на рабочее топливо, %</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Общая влага рабочего топлива, %</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Содержа-ние серы на сухое состояние, %</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Выход летучих веществ, %</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Низшая теплота сгорания на рабочее&#160; топливо, ккал/кг</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Толщина пластического слоя (для углей для коксования), мм</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>А</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Б</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>В</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>4</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>5</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>6</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>7</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strdata_020">
											<tr>
												<td>
													<xsl:for-each select="@name">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td/>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column4">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column5">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column6">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column7">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Раздел III. Использование фонда времени экскаваторов за отчетный год (часов)</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_2" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th rowspan="2">
									<span>
										<xsl:text>Виды работ</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<br/>
									<br/>
									<span>
										<xsl:text>№ строки</xsl:text>
									</span>
									<br/>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Календарный фонд</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>времени</xsl:text>
									</span>
									<br/>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Число часов работы</xsl:text>
									</span>
									<br/>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>В том числе в перегоне</xsl:text>
									</span>
									<br/>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>ППР</xsl:text>
									</span>
									<br/>
								</th>
								<th colspan="2">
									<span>
										<xsl:text>Регламентируемые простои</xsl:text>
									</span>
								</th>
								<th colspan="5">
									<span>
										<xsl:text>Непланируемые простои</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>связанные с режимом работы экскаватора</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Выходные и праздничные дни</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Всего, из них</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>аварии и неполадки с экскаваторами</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Неподготовленность рабочего места</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>плохое состояние путей, аварии на транспорте</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>отсутствие средств</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>транспорта</xsl:text>
									</span>
									<br/>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>А</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Б</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>4</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>5</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>6</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>7</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>8</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>9</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>10</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>11</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strdata_030">
											<tr>
												<td>
													<xsl:for-each select="@name">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column4">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column5">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column6">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column7">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column8">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column9">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column10">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column11">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<span>
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<br/>
				<span>
					<xsl:text>Раздел IV. Показатели работы экскаваторов и погрузчиков за отчетный год</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_3" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Наименование</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>№ строки</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Среднесписочное число, шт.</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Объем работ,</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>тыс. м3</xsl:text>
									</span>
									<br/>
								</th>
								<th>
									<span>
										<xsl:text>Объем работ, тонн</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>А</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Б</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strdata_040">
											<tr>
												<td>
													<xsl:for-each select="@name">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Раздел V. Добыча угля и вскрышные работы по видам выемки и транспортировки за отчетный год</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_4" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<tbody>
							<tr>
								<td rowspan="2" style="text-align:center; ">
									<span>
										<xsl:text>На</xsl:text>
									</span>
									<span style="font-weight:bold; ">
										<xsl:text>именование</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>№ строки</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Ед.</xsl:text>
									</span>
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>изм.</xsl:text>
									</span>
								</td>
								<td colspan="5" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Экскаваторами</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Гидравлическим способом</xsl:text>
									</span>
								</td>
								<td colspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Прочими способами (указать какими)</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Всего</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>на ж.-д. транспорт</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>на конвейеры</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>на авто-транспорт</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>вскрыша отвальными мостами</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>бестранспортная вскрыша</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>всего</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>в т.ч. погрузчиками</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>А</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Б</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>В</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>1</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>2</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>3</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>4</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>5</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>6</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>7</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>8</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>9</xsl:text>
									</span>
								</td>
							</tr>
							<tr style="height:0.24in; ">
								<td>
									<span>
										<xsl:text>Добыча</xsl:text>
									</span>
								</td>
								<td>
									<span>
										<xsl:text>01</xsl:text>
									</span>
								</td>
								<td>
									<span>
										<xsl:text>тыс. т</xsl:text>
									</span>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=1]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=6]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=3]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=7]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=4]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=74]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=75]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=76]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=72]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td>
									<span>
										<xsl:text>Вскрыша</xsl:text>
									</span>
								</td>
								<td>
									<span>
										<xsl:text>02</xsl:text>
									</span>
								</td>
								<td>
									<span>
										<xsl:text>тыс. м3</xsl:text>
									</span>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=1]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=6]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=3]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=7]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=4]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=74]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=75]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=76]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_050[@code=72]">
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<br/>
				<span>
					<xsl:text>Раздел VI.&#160; Показатели работы локомотивосоставов, занятых на транспортировке вскрыши</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_5" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>№ п/п</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Наименование локомотива</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>(с составами)</xsl:text>
									</span>
									<br/>
								</th>
								<th>
									<span>
										<xsl:text>Среднемесячное количество локомотивосоставов по списку</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Всего погружено локомотивосоставов</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>за год</xsl:text>
									</span>
									<br/>
								</th>
								<th>
									<span>
										<xsl:text>Количество вывезенной вскрышной породы,</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>тыс. м3</xsl:text>
									</span>
									<br/>
								</th>
								<th>
									<span>
										<xsl:text>Среднее расстояние транспортировки,</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>км </xsl:text>
									</span>
									<br/>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>А</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Б</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>4</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strdata_060">
											<tr>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@name">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column4">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Раздел VII. Показатели работы буровых станков за отчетный год</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_6" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th rowspan="2">
									<span>
										<xsl:text>Наименование</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>№ строки</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Пробурено за год, пог.м</xsl:text>
									</span>
								</th>
								<th colspan="2">
									<span>
										<xsl:text>Среднемесячное количество станков</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Отработано за год станкосмен</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Среднемесячная произво-дительность списочного станка (гр.1:гр.2):12</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>по списку</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>в работе</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>А</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Б</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>4</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>5</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strdata_070">
											<tr>
												<td>
													<xsl:for-each select="@name">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column4">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column5">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Раздел VIII. Наличие и использование оборудования на конец отчетного года</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1">
						<xsl:variable name="altova:CurrContextGrid_7" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<thead>
							<tr>
								<th rowspan="2">
									<span>
										<xsl:text>Наименование</xsl:text>
									</span>
									<br/>
									<span>
										<xsl:text>(тип и марка)</xsl:text>
									</span>
									<br/>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>№ строки</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Единица измерения</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>В нали-чии</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>В том числе в работе</xsl:text>
									</span>
								</th>
								<th colspan="2">
									<span>
										<xsl:text>За отчетный год</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Из общего наличия (гр.1)арендованное</xsl:text>
									</span>
								</th>
								<th rowspan="2">
									<span>
										<xsl:text>Из арендованного -по лизингу</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>Списано</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Приобретено</xsl:text>
									</span>
								</th>
							</tr>
							<tr>
								<th>
									<span>
										<xsl:text>А</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Б</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>В</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>1</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>2</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>3</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>4</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>5</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>6</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="$XML">
								<xsl:for-each select="document">
									<xsl:for-each select="flat">
										<xsl:for-each select="strdata_080">
											<tr>
												<td>
													<xsl:for-each select="@name">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@code">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td/>
												<td>
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column2">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column3">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column4">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column5">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="@column6">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Раздел IX. Численность персонала и производительность труда за отчетный год</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_8" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<tbody>
							<tr>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Наименова</xsl:text>
									</span>
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>ние</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>№ строки</xsl:text>
									</span>
								</td>
								<td colspan="5" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Среднесписочная численность</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Всего персонала на конец отчетного года </xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Добыча уг-ля, приня-тая к учету для определения произво-дительности труда</xsl:text>
									</span>
								</td>
								<td colspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Среднемесячная производительность труда</xsl:text>
									</span>
								</td>
								<td rowspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Отработано человеко-дней рабочими по добыче угля</xsl:text>
									</span>
								</td>
								<td colspan="2" style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Из них:</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>рабочие на добычных работах</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>рабочие на вскрышных работах</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>рабочие прочих цехов</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>рабочие по добыче угля) (гр.1+гр.2</xsl:text>
									</span>
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>+гр.3)</xsl:text>
									</span>
									<br/>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>всего работников по основному виду деятельности</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>рабочего по добыче угля (гр.7:гр.4) :12, т</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>рабочего на вскрыше, м3</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>на добычных работах</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>на вскрышных работах</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>А</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Б</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>1</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>2</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>3</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>4</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>5</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>6</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>7</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>8</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>9</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>10</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>11</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>12</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td>
									<span>
										<xsl:text>Фактически</xsl:text>
									</span>
								</td>
								<td>
									<span>
										<xsl:text>01</xsl:text>
									</span>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=148]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=149]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=150]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=151]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=152]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=153]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=154]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=155]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=156]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=157]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=158]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
								<td>
									<xsl:for-each select="$XML">
										<xsl:for-each select="document">
											<xsl:for-each select="flat">
												<xsl:for-each select="strdata_090[@code=159]">
													<xsl:for-each select="@column1">
														<span>
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>Распределение акций по акционерам</xsl:text>
				</span>
				<br/>
				<xsl:variable name="altova:table">
					<table border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_9" select="."/>
						<xsl:variable name="altova:ColumnData"/>
						<tbody>
							<tr>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>№п/п</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Наименование</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>Количество акций</xsl:text>
									</span>
								</td>
								<td style="text-align:center; ">
									<span style="font-weight:bold; ">
										<xsl:text>% от уставного капитала</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td/>
								<td/>
								<td/>
								<td/>
							</tr>
							<tr>
								<td/>
								<td/>
								<td/>
								<td/>
							</tr>
							<tr>
								<td/>
								<td/>
								<td/>
								<td/>
							</tr>
							<tr>
								<td/>
								<td/>
								<td/>
								<td/>
							</tr>
						</tbody>
					</table>
				</xsl:variable>
				<xsl:variable name="altova:col-count" select="sum( for $altova:cell in $altova:table/table/(thead | tbody | tfoot)[ 1 ]/tr[ 1 ]/(th | td) return altova:col-span( $altova:cell ) )"/>
				<xsl:variable name="altova:generate-cols" as="xs:boolean*" select="for $altova:pos in 1 to $altova:col-count return true()"/>
				<xsl:apply-templates select="$altova:table" mode="altova:generate-table">
					<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
				</xsl:apply-templates>
				<br/>
				<span>
					<xsl:text>«____» ___________20__ год</xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>(дата предоставления</xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text> информации в </xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>государственную информационную </xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>систему топливно-энергетического </xsl:text>
				</span>
				<br/>
				<span>
					<xsl:text>комплекса)</xsl:text>
				</span>
				<br/>
				<br/>
			</body>
		</html>
	</xsl:template>
	<xsl:function name="altova:is-cell-empty" as="xs:boolean">
		<xsl:param name="altova:cell" as="element()"/>
		<xsl:sequence select="altova:is-node-empty( $altova:cell )"/>
	</xsl:function>
	<xsl:function name="altova:is-node-empty" as="xs:boolean">
		<xsl:param name="altova:node" as="element()"/>
		<xsl:sequence select="every $altova:child in $altova:node/child::node() satisfies ( ( boolean( $altova:child/self::text() ) and string-length( $altova:child ) = 0 ) or ( ( boolean( $altova:child/self::div ) or boolean( $altova:child/self::span ) or boolean( $altova:child/self::a ) ) and altova:is-node-empty( $altova:child ) ) )"/>
	</xsl:function>
	<xsl:function name="altova:col-span" as="xs:integer">
		<xsl:param name="altova:cell" as="element()"/>
		<xsl:sequence select="if ( exists( $altova:cell/@colspan ) ) then xs:integer( $altova:cell/@colspan ) else 1"/>
	</xsl:function>
	<xsl:template match="@* | node()" mode="altova:generate-table">
		<xsl:param name="altova:generate-cols"/>
		<xsl:copy>
			<xsl:apply-templates select="@* | node()" mode="#current">
				<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
			</xsl:apply-templates>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="tbody" mode="altova:generate-table">
		<xsl:param name="altova:generate-cols"/>
		<xsl:choose>
			<xsl:when test="empty(tr)">
				<xsl:copy>
					<tr>
						<td/>
					</tr>
				</xsl:copy>
			</xsl:when>
			<xsl:otherwise>
				<xsl:copy>
					<xsl:apply-templates select="@* | node()" mode="#current">
						<xsl:with-param name="altova:generate-cols" select="$altova:generate-cols"/>
					</xsl:apply-templates>
				</xsl:copy>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template match="th | td" mode="altova:generate-table">
		<xsl:choose>
			<xsl:when test="altova:is-cell-empty( . )">
				<xsl:copy>
					<xsl:apply-templates select="@*" mode="#current"/>
					<xsl:text>&#160;</xsl:text>
				</xsl:copy>
			</xsl:when>
			<xsl:otherwise>
				<xsl:copy>
					<xsl:apply-templates select="@* | node()" mode="#current"/>
				</xsl:copy>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:function name="altova:GetChartYValuesForSingleSeries">
		<xsl:param name="seqCategoryLeafPos" as="node()*"/>
		<xsl:param name="nodeSeriesLeafPos" as="node()"/>
		<xsl:param name="bValuesInCategory" as="xs:boolean"/>
		<xsl:for-each select="$seqCategoryLeafPos">
			<xsl:element name="altova:Value">
				<xsl:value-of select="altova:GetChartYValueForSingleSeriesPos($nodeSeriesLeafPos, ., $bValuesInCategory)"/>
			</xsl:element>
		</xsl:for-each>
	</xsl:function>
	<xsl:function name="altova:GetChartYValueForSingleSeriesPos">
		<xsl:param name="nodeSeriesLeafPos" as="node()"/>
		<xsl:param name="nodeCategoryLeafPos" as="node()"/>
		<xsl:param name="bValuesInCategory" as="xs:boolean"/>
		<xsl:variable name="altova:seqCategoryContextIds" select="$nodeCategoryLeafPos/altova:Context/@altova:ContextId" as="xs:string*"/>
		<xsl:variable name="altova:seqSeriesContextIds" select="$nodeSeriesLeafPos/altova:Context/@altova:ContextId" as="xs:string*"/>
		<xsl:variable name="altova:sCommonContextId" select="for $i in $altova:seqCategoryContextIds return if (some $j in $altova:seqSeriesContextIds satisfies $i eq $j) then $i else ()" as="xs:string*"/>
		<xsl:choose>
			<xsl:when test="count($altova:sCommonContextId) gt 1">
				<xsl:message select="concat('Found several values instead of a single one (contexts: ', string-join($altova:sCommonContextId, ', '), ').')" terminate="yes"/>
			</xsl:when>
			<xsl:when test="count($altova:sCommonContextId) lt 1">
				<xsl:message select="concat('XBRL Chart: Info: No value found for position labeled &quot;', $nodeCategoryLeafPos/@altova:sLabel, '&quot;')" terminate="no"/>
				<xsl:sequence select="'altova:no-value'"/>
			</xsl:when>
			<xsl:when test="$bValuesInCategory">
				<xsl:sequence select="xs:string($nodeCategoryLeafPos/altova:Context[@altova:ContextId eq $altova:sCommonContextId]/@altova:Value)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:sequence select="xs:string($nodeSeriesLeafPos/altova:Context[@altova:ContextId eq $altova:sCommonContextId]/@altova:Value)"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>
	<xsl:function name="altova:GetChartLabelForPos" as="xs:string">
		<xsl:param name="nodeParam" as="node()"/>
		<xsl:value-of select="string-join($nodeParam/ancestor-or-self::altova:Pos/@altova:sLabel, ' ')"/>
	</xsl:function>
	<xsl:function name="altova:convert-length-to-pixel" as="xs:decimal">
		<xsl:param name="altova:length"/>
		<xsl:variable name="normLength" select="normalize-space($altova:length)"/>
		<xsl:choose>
			<xsl:when test="ends-with($normLength, 'px')">
				<xsl:value-of select="substring-before($normLength, 'px')"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'in')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'in')) * $altova:nPxPerIn"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'cm')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'cm')) * $altova:nPxPerIn div 2.54"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'mm')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'mm')) * $altova:nPxPerIn div 25.4"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pt')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pt')) * $altova:nPxPerIn div 72.0"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pc')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pc')) * $altova:nPxPerIn div 6.0"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$normLength"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>
	<xsl:function name="altova:convert-length-to-mm" as="xs:decimal">
		<xsl:param name="altova:length"/>
		<xsl:variable name="normLength" select="normalize-space($altova:length)"/>
		<xsl:choose>
			<xsl:when test="ends-with($normLength, 'px')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'px')) div $altova:nPxPerIn * 25.4"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'in')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'in')) * 25.4"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'cm')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'cm')) * 10"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'mm')">
				<xsl:value-of select="substring-before($normLength, 'mm') "/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pt')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pt')) * 25.4 div 72.0"/>
			</xsl:when>
			<xsl:when test="ends-with($normLength, 'pc')">
				<xsl:value-of select="xs:decimal(substring-before($normLength, 'pc')) * 25.4 div 6.0"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="number($normLength) div $altova:nPxPerIn * 25.4"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>
</xsl:stylesheet>
